# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92ddf8602ba4c0860d289fd8b067d3f5906f6fb8a02d70e805770943618ab7f2b8d9636456a884d0eadc051dadb34b8ea9287a792cf00243acea472f787dcb8

test:
  secret_key_base: b6689e994565d1083b1579c79bc626bb7a6e53d116689f2167f9b984a55d88f2e23a2b5df314624ee8268f43cb979b9888cff9bd2dd86a67d7a05cdd2b072839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
